let truths = [
    "Pernah stalk akun sosmed mantan atau gebetan di jam 3 pagi?",
    "Siapa nama kontak paling aneh yang pernah kamu simpan di HP?",
    "Kalau bisa ngilangin satu orang dari hidup lo, siapa orang itu?",
    "Pernah nggak, kepikiran buat ngechat mantan pas lagi galau berat?",
    "Kapan terakhir kali kamu bohong ke orang tua dan soal apa?",
    "Siapa orang yang paling sering muncul di mimpi lo?",
    "Apakah kamu percaya bahwa kita dipertemukan karena takdir?",
    "Menurutmu, apakah jodoh itu datang karena usaha atau hanya menunggu waktu yang tepat?",
    "Bagaimana cara kita tahu jika seseorang adalah jodoh kita?",
    "Apakah jodoh itu sesuatu yang pasti, atau bisa berubah tergantung pilihan kita?",
    "Kenapa kita sering merasa ragu meskipun hati sudah merasa cocok?",
    "Jika kita berpisah, apakah menurutmu itu artinya kita bukan jodoh?",
    "Apa yang membuatmu yakin aku adalah bagian dari takdirmu?",
    "Kenapa kita dipertemukan jika akhirnya harus terpisah?",
    "Menurutmu, apakah jodoh itu datang dengan mudah atau harus diperjuangkan?",
    "Jika kita adalah jodoh, kenapa jalan kita terasa begitu sulit?",
    "Apa yang kamu rasakan ketika memikirkan tentang takdir dan jodoh kita?",
    "Kenapa kita harus mengalami luka jika pada akhirnya jodoh akan menyembuhkan?",
    "Apakah kamu percaya bahwa Tuhan punya rencana indah untuk hubungan kita?",
    "Kenapa kita dipertemukan jika kita tidak ditakdirkan untuk bersama?",
    "Apa yang membuatmu yakin bahwa jodoh itu adalah seseorang yang sempurna?",
    "Apakah menurutmu jodoh adalah seseorang yang selalu membuat kita bahagia?",
    "Kenapa kita sering merasa takut kehilangan jika jodoh pasti tidak akan pergi?",
    "Apakah jodoh itu harus selalu dirasakan sejak awal atau bisa tumbuh seiring waktu?",
    "Bagaimana menurutmu cara terbaik untuk menerima takdir yang tidak sesuai harapan?",
    "Kenapa kita sering mempertanyakan jodoh jika Tuhan sudah mengaturnya?",
    "Apakah menurutmu aku termasuk dalam rencana masa depanmu sebagai jodoh?",
    "Jika aku bukan jodohmu, apakah kamu akan tetap bersyukur atas pertemuan kita?",
    "Apakah jodoh itu seseorang yang selalu mendukung kita, atau yang mengajarkan pelajaran hidup?",
    "Kenapa kita sering merasa ragu pada hubungan yang Tuhan pertemukan?",
    "Apakah menurutmu takdir itu bisa berubah karena pilihan kita?",
    "Kenapa kita sering berdoa tentang jodoh, tapi sulit menerima jawabannya?",
    "Apakah menurutmu ada alasan Tuhan membuat perjalanan kita seperti ini?",
    "Jika aku adalah takdirmu, kenapa jalannya terasa begitu rumit?",
    "Apa yang kamu yakini tentang konsep jodoh dalam hidupmu?",
    "Apakah menurutmu takdir kita akan membawa kita kembali bersama jika saat ini kita terpisah?",
    "Kenapa banyak orang bertemu tapi tidak berakhir bersama, apakah itu bukan takdir?",
    "Bagaimana kamu membedakan cinta yang datang sebagai jodoh dan yang hanya sementara?",
    "Apa yang kamu pikirkan tentang takdir ketika kita sedang dalam konflik?",
    "Kenapa kita sering merasa takut kehilangan sesuatu yang sudah ditakdirkan untuk kita?",
    "Apakah menurutmu takdir jodoh itu sesuatu yang harus dicari atau akan datang sendiri?",
    "Jika takdir kita adalah bersama, apa yang harus kita lakukan untuk memastikannya?",
    "Apakah kamu percaya bahwa jodoh kita sudah tertulis sebelum kita dilahirkan?",
    "Apa yang membuatmu yakin atau tidak yakin bahwa aku adalah jodohmu?",
    "Kenapa kita sering menyalahkan takdir jika hubungan tidak berjalan sesuai harapan?",
    "Apakah menurutmu jodoh itu harus selalu sempurna di mata kita?",
    "Bagaimana kita tahu bahwa kita sudah menemukan jodoh yang tepat?",
    "Apakah menurutmu takdir bisa berubah karena keputusan yang kita buat?",
    "Kenapa kita sering merasa bingung antara takdir dan pilihan hidup?",
    "Apakah menurutmu aku adalah bagian dari perjalanan takdirmu?",
    "Jika kita bukan jodoh, apakah kamu percaya bahwa kita bertemu untuk alasan tertentu?",
    "Kenapa kita selalu berharap pada seseorang yang belum tentu takdir kita?",
    "Apa yang membuatmu percaya pada konsep jodoh yang sudah ditentukan?",
    "Bagaimana menurutmu cara terbaik menerima jika aku bukan jodohmu?",
    "Apakah menurutmu takdir jodoh itu selalu membawa kebahagiaan?",
    "Apa yang membuatmu yakin bahwa Tuhan punya rencana terbaik untuk hubungan kita?",
    "Lebih suka pacaran diam-diam atau pamer di sosmed?",
"Apa hal yang paling kamu suka dari pasanganmu?",
    "Apa kebiasaan pasanganmu yang menurutmu menggemaskan?",
    "Pernah nggak kamu bohong sama pasanganmu?",
    "Kalau pasanganmu nggak setuju sama keputusanmu, apa kamu tetap lanjut?",
    "Apa kamu pernah curiga sama pasanganmu?",
    "Pernah nggak kamu stalking media sosial pasanganmu diam-diam?",
    "Kalau pasanganmu marah, apa yang biasanya kamu lakukan?",
    "Apa pasanganmu pernah melakukan sesuatu yang bikin kamu kecewa?",
    "Kalau pasanganmu tiba-tiba minta putus tanpa alasan jelas, apa reaksi kamu?",
    "Apa kamu pernah pura-pura suka sesuatu demi menyenangkan pasanganmu?",
    "Pernah nggak kamu terpikir untuk selingkuh?",
    "Apa menurutmu selingkuh itu hanya soal fisik atau bisa juga emosional?",
    "Kalau tahu pasanganmu selingkuh, apa kamu langsung putus?",
    "Apa kamu bisa memaafkan pasangan yang selingkuh?",
    "Apa kamu pernah selingkuh di hubungan sebelumnya?",
    "Menurutmu, apa alasan orang selingkuh?",
    "Pernah nggak kamu merasa lebih tertarik ke orang lain saat masih pacaran?",
    "Kalau sahabatmu tahu pasanganmu selingkuh, apa kamu ingin mereka kasih tahu kamu?",
    "Apa kamu percaya bahwa sekali selingkuh, selalu selingkuh?",
    "Pernah nggak kamu ngetes pasanganmu dengan orang lain untuk lihat apakah dia setia?",
    "Apa kamu pernah pura-pura mencintai seseorang?",
    "Pernah nggak kamu merasa bosan dengan pasanganmu?",
    "Apa kamu masih ingat momen pertama kali kamu sadar kamu jatuh cinta sama pasanganmu?",
    "Apa kamu pernah merasa cinta pasanganmu berubah?",
    "Apa yang akan kamu lakukan kalau kamu merasa nggak cinta lagi sama pasanganmu?",
    "Apa kamu bisa bersama seseorang tanpa cinta?",
    "Kalau pasanganmu bilang dia nggak cinta lagi, apa kamu tetap bertahan?",
    "Apa kamu pernah pacaran hanya karena kasihan?",
    "Menurutmu, apa cinta bisa balik lagi setelah hilang?",
    "Apa kamu pernah merasa pasanganmu nggak seantusias dulu?",
    "Apa kamu pernah membayangkan menikah dengan pasanganmu?",
    "Menurutmu, apa pasanganmu adalah tipe yang cocok jadi suami/istri?",
    "Kalau pasanganmu pindah ke kota lain, apa kamu mau ikut?",
    "Apa kamu mau punya anak dari pasanganmu?",
    "Apa kamu pernah memikirkan berapa lama hubunganmu bisa bertahan?",
    "Kalau pasanganmu punya mimpi yang jauh beda sama kamu, apa kamu bisa mendukungnya?",
    "Apa kamu yakin pasanganmu bisa jadi orang tua yang baik?",
    "Menurutmu, hubungan jarak jauh bisa berhasil nggak?",
    "Apa kamu lebih memilih karier atau pasanganmu?",
    "Apa pasanganmu tahu semua rencana masa depanmu?",
    "Pernah nggak kamu membandingkan pasanganmu dengan mantan?",
    "Apa kamu masih kontak sama mantan?",
    "Apa kamu pernah memikirkan mantan saat bersama pasanganmu?",
    "Kalau mantanmu balik minta kesempatan kedua, apa kamu terima?",
    "Apa pasanganmu tahu semua tentang masa lalu cintamu?",
    "Apa ada mantan yang masih kamu anggap spesial?",
    "Pernah nggak kamu ngintip media sosial mantan?",
    "Apa menurutmu mantan dan pacar bisa jadi teman?",
    "Pernah nggak kamu bermimpi tentang mantan?",
    "Apa kamu pernah merasa mantan lebih perhatian dari pasanganmu sekarang?",
    "Seberapa besar kamu percaya pada pasanganmu?",
    "Apa kamu tahu semua password pasanganmu?",
    "Kalau pasanganmu nggak jujur tentang sesuatu kecil, apa itu masalah besar buatmu?",
    "Apa kamu percaya cinta tanpa kepercayaan bisa bertahan?",
    "Pernah nggak pasanganmu melanggar janji?",
    "Kalau pasanganmu bohong demi kebaikan, apa itu bisa dimaafkan?",
    "Apa kamu sering mengecek HP pasanganmu?",
    "Kalau pasanganmu nggak cerita tentang sesuatu, apa kamu akan memaksa dia cerita?",
    "Apa kamu pernah pura-pura nggak tahu kebohongan pasanganmu?",
    "Apa kamu sering merasa insecure di hubunganmu?",
    "Apa kamu pernah bertengkar hebat dengan pasanganmu?",
    "Kalau pasanganmu salah, apakah dia sering minta maaf duluan?",
    "Apa kamu sering ngalah demi menghindari konflik?",
    "Menurutmu, pasanganmu lebih keras kepala atau fleksibel?",
    "Apa kamu bisa menyelesaikan masalah dengan pasanganmu tanpa teriak-teriak?",
    "Kalau pasanganmu membahas masalah lama, apa kamu akan marah?",
    "Apa kamu pernah mengabaikan pasanganmu saat marah?",
    "Kalau pasanganmu nangis karena kamu, apa yang akan kamu lakukan?",
    "Apa kamu bisa memaafkan pasanganmu tanpa dendam?",
    "Apa pasanganmu pernah melibatkan orang lain dalam masalah kalian?",
    "Apa kamu sudah jadi pasangan yang baik menurutmu?",
    "Apa kamu sering memprioritaskan pasanganmu dibanding dirimu sendiri?",
    "Kalau pasanganmu nggak suka sesuatu tentang dirimu, apa kamu akan berubah?",
    "Apa kamu merasa pasanganmu cukup menghargai kamu?",
    "Apa kamu percaya pasanganmu lebih baik darimu?",
    "Kalau pasanganmu sukses lebih dulu dari kamu, apa kamu akan minder?",
    "Pernah nggak kamu merasa pasanganmu lebih butuh kamu daripada kamu butuh dia?",
    "Apa pasanganmu tahu kelemahan terbesarmu?",
    "Apa kamu sering cerita ke pasanganmu tentang masalahmu?",
    "Apa pasanganmu mendukung impianmu?",
    "Apa momen paling lucu yang pernah terjadi di hubungan kalian?",
    "Apa kamu percaya cinta pada pandangan pertama?",
    "Kalau kamu punya kekuatan membaca pikiran pasangan, apa yang pertama ingin kamu tahu?",
    "Apa yang kamu pikirkan saat pertama kali bertemu pasanganmu?",
    "Kalau pasanganmu bikin kesalahan besar, apa kamu akan tetap mendukungnya?",
    "Apa menurutmu hubungan kalian butuh lebih banyak usaha?",
    "Apa ada hal yang belum pernah kamu bilang ke pasanganmu?",
    "Kalau hubungan kalian berakhir, apa kamu masih bisa berteman?",
    "Apa pasanganmu adalah orang yang kamu cari selama ini?",
    "Apa kamu pernah diam-diam nggak suka keputusan pasanganmu?",
    "Apa pasanganmu tahu semua teman dekatmu?",
    "Apa kamu pernah membayangkan pasanganmu melakukan sesuatu yang nggak pernah dia lakukan?",
    "Apa kamu pernah pura-pura tertarik pada sesuatu yang disukai pasanganmu?",
    "Kalau pasanganmu sedang sibuk, apa kamu akan tetap menghubunginya?",
    "Apa pasanganmu tahu semua hobimu?",
    "Kenapa kita masih bersama jika kita sudah tidak saling mencintai?",
    "Apakah kita bertahan hanya karena takut memulai semuanya dari awal?",
    "Apa yang membuatmu yakin hubungan ini masih layak diperjuangkan?",
    "Apakah kamu masih bahagia berada di hubungan ini, atau hanya bertahan karena terbiasa?",
    "Kenapa kita tetap bersama meskipun sering merasa lelah dengan hubungan ini?",
    "Apa yang sebenarnya kamu cari dalam hubungan ini sekarang?",
    "Apakah aku masih menjadi prioritas dalam hidupmu, atau hanya sekadar kewajiban?",
    "Apa yang kamu rasakan ketika kita sudah jarang bicara dari hati ke hati?",
    "Kenapa kita lebih sering menghindari masalah daripada menyelesaikannya?",
    "Apa yang membuatmu tetap di sini meskipun cinta sudah tidak ada?",
    "Apakah kamu merasa aku masih bisa membuatmu bahagia seperti dulu?",
    "Apa yang kamu rasakan saat mengingat momen bahagia kita dulu?",
    "Apakah kita hanya bertahan demi mempertahankan status sebagai pasangan?",
    "Kenapa kita lebih sering bertengkar daripada saling memahami?",
    "Menurutmu, apakah kita tetap bersama hanya untuk menjaga perasaan orang lain?",
    "Apa yang kamu pikirkan saat aku bilang aku merasa hubungan ini mulai kosong?",
    "Kenapa kita lebih sering merasa sendiri meskipun bersama?",
    "Apa yang membuat kita masih bertahan meskipun tahu hubungan ini tidak sehat?",
    "Apakah kita hanya memaksakan hubungan ini karena sudah terlalu lama bersama?",
    "Jika cinta sudah hilang, apa alasan kita masih terus bertahan?",
    "Kenapa kita lebih sering menghindari percakapan penting daripada menyelesaikan masalah?",
    "Apa yang kamu harapkan dari hubungan ini ke depannya?",
    "Kenapa kita tetap bersama padahal sudah tidak ada rasa cinta?",
    "Apakah menurutmu hubungan ini masih memiliki tujuan yang jelas?",
    "Apa yang kamu rasakan ketika aku tidak ada di dekatmu?",
    "Kenapa kita lebih sering memikirkan kenangan masa lalu daripada masa depan?",
    "Apakah kamu merasa kita hanya bertahan karena takut menyakiti satu sama lain?",
    "Apa yang membuatmu yakin kita bisa memperbaiki hubungan ini?",
    "Menurutmu, apa yang lebih sulit: meninggalkan hubungan ini atau tetap bertahan?",
    "Apa yang kamu pikirkan saat aku mencoba berbicara tentang perasaan kita?",
    "Kenapa kita tetap bersama meskipun cinta itu sudah tidak ada?",
    "Apakah kita masih bersama karena rasa nyaman atau rasa takut kehilangan?",
    "Apakah kamu merasa hubungan ini lebih seperti beban daripada kebahagiaan?",
    "Apa yang kamu rasakan ketika kita sudah jarang menunjukkan kasih sayang satu sama lain?",
    "Apakah kamu yakin kita masih memiliki masa depan bersama?",
    "Kenapa kita lebih sering merasa lelah dengan hubungan ini daripada bahagia?",
    "Apakah kamu merasa aku masih menjadi orang yang kamu inginkan di masa depan?",
    "Apa yang membuatmu ragu untuk meninggalkan hubungan ini?",
    "Menurutmu, apa alasan terbesar kita bertahan sejauh ini?",
    "Apa yang kamu pikirkan saat melihat pasangan lain terlihat bahagia?",
    "Kenapa kita tidak pernah benar-benar jujur tentang apa yang kita rasakan?",
    "Apa yang menurutmu salah dalam hubungan kita sekarang?",
    "Apakah kamu merasa kita hanya bertahan karena takut menghadapi kenyataan?",
    "Kenapa kita tetap bersama meskipun lebih banyak luka daripada kebahagiaan?",
    "Apa tujuan kita sebenarnya dalam hubungan ini?",
    "Apakah kamu merasa aku masih memberikan perhatian yang kamu butuhkan?",
    "Kenapa kita lebih sering berpura-pura bahagia di depan orang lain?",
    "Apa yang membuatmu tetap bertahan meskipun hati sudah tidak ada di sini?",
    "Apa yang kamu rasakan saat aku mencoba menunjukkan rasa sayang padamu?",
    "Apakah kamu merasa hubungan ini lebih seperti kewajiban daripada keinginan?",
    "Kenapa kita terus bertahan meskipun tidak ada cinta yang tersisa?",
    "Apa yang membuatmu tidak ingin melepas hubungan ini meskipun sudah tidak bahagia?",
    "Kenapa kita lebih sering merasa terjebak daripada saling mendukung?",
    "Apa yang membuatmu yakin kita masih bisa bahagia bersama?",
    "Kenapa kita lebih sering menghindari masalah daripada menyelesaikannya?",
    "Apa yang kamu pikirkan saat aku mengatakan aku lelah dengan hubungan ini?",
    "Apakah kamu merasa hubungan ini masih memiliki arti?",
    "Kenapa kita lebih sering saling menyakiti daripada saling mencintai?",
    "Apakah kita bertahan hanya karena takut merasa sendiri?",
    "Apa yang membuatmu yakin hubungan ini masih layak diperjuangkan?",
    "Apa yang kamu rasakan ketika kita semakin jarang berbicara satu sama lain?",
    "Apakah menurutmu hubungan tanpa cinta masih bisa disebut hubungan?",
    "Kenapa kita tetap bersama jika sudah tidak ada lagi kebahagiaan?",
    "Apa yang kamu harapkan dari hubungan ini sekarang?",
    "Kenapa kita lebih sering mengingat masa lalu daripada membangun masa depan?",
    "Apakah kamu merasa aku masih menjadi orang yang kamu butuhkan?",
    "Kenapa kita terus bersama meskipun kita tahu cinta itu sudah hilang?",
    "Apa yang kamu pikirkan saat aku mencoba untuk lebih dekat denganmu?",
    "Kenapa kita tetap bersama jika kita tahu hubungan ini tidak sehat?",
    "Apa yang kamu rasakan ketika aku mengatakan hubungan ini tidak lagi sama?",
    "Apakah menurutmu kita hanya bertahan karena takut dengan perubahan?",
    "Apa yang membuatmu yakin kita bisa memperbaiki hubungan ini?",
    "Kenapa kita tetap saling menyakiti meskipun masih bersama?",
    "Apakah kamu merasa hubungan ini lebih banyak memberikan luka daripada kebahagiaan?",
    "Kenapa kita terus bertahan meskipun tahu ini tidak akan berhasil?",
    "Apa yang kamu rasakan saat kita semakin jarang menunjukkan rasa cinta?",
    "Apakah kamu yakin hubungan ini masih memiliki tujuan yang jelas?",
    "Kenapa kita tetap bersama jika lebih banyak rasa sakit daripada cinta?",
    "Apa yang kamu pikirkan saat aku mencoba membicarakan masa depan kita?",
    "Kenapa kita tetap bersama meskipun cinta sudah tidak ada?",
    "Apa yang kamu harapkan dari hubungan ini ke depannya?",
    "Kenapa kita terus berpura-pura bahagia meskipun hati kita tahu kebenarannya?",
    "Apakah kamu merasa hubungan ini masih layak diperjuangkan?",
    "Apa yang kamu pikirkan saat aku menunjukkan usaha untuk mempertahankan kita?",
    "Kenapa kita lebih sering merasa sendiri meskipun bersama?",
    "Apa yang membuatmu yakin kita masih memiliki masa depan bersama?",
    "Kenapa kita tidak pernah benar-benar menyelesaikan masalah yang ada?",
    "Apakah kamu merasa aku masih menjadi orang yang kamu inginkan?",
    "Kenapa kita tetap bersama meskipun lebih banyak luka daripada kebahagiaan?",
    "Apa kamu merasa pasanganmu cukup tahu tentang dirimu?",
    "Kalau kamu harus mendeskripsikan pasanganmu dalam tiga kata, apa yang akan kamu pilih?",
    "Apa kamu pernah merasa nggak pantas untuk pasanganmu?",
    "Apa kamu lebih suka pasanganmu menjadi lebih romantis?",
    "Apa kamu merasa pasanganmu adalah cinta sejati?",
    "Apa kamu masih punya rasa sama mantanmu?",
    "Menurutmu, apa alasan terbesar hubungan kita dulu berakhir?",
    "Jika kita balikan, apa yang akan kamu lakukan berbeda dari sebelumnya?",
    "Apa kenangan terbaik yang kamu miliki tentang hubungan kita?",
    "Apakah kamu pernah merasa hubungan kita dulu bisa berhasil jika diberi kesempatan kedua?",
    "Menurutmu, apa yang salah dengan hubungan kita dulu?",
    "Apakah kamu pernah merasa aku kurang berusaha mempertahankan hubungan kita?",
    "Apa perasaanmu saat mengingat momen kita yang paling bahagia?",
    "Jika ada orang ketiga dalam hubungan kita dulu, apakah kamu tahu siapa yang salah?",
    "Apakah kamu merasa kita pernah mencoba terlalu keras untuk mempertahankan hubungan yang sudah rusak?",
    "Menurutmu, apakah aku orang yang paling mengerti kamu?",
    "Apa yang membuatmu bertahan saat hubungan kita mulai sulit?",
    "Menurutmu, apakah cinta saja cukup untuk membuat hubungan berhasil?",
    "Jika kita menikah, apakah kamu merasa kita akan bisa menyelesaikan masalah kita?",
    "Apa hal terbesar yang menurutmu harus aku perbaiki jika kita mencoba lagi?",
    "Apa yang kamu pikirkan tentang pasangan yang memilih untuk memaafkan perselingkuhan?",
    "Apakah kamu percaya aku akan tetap setia jika kita balikan?",
    "Apa yang kamu rasakan saat mendengar aku dekat dengan orang lain?",
    "Apakah kamu pernah merasa aku lebih peduli pada orang lain dibandingkan dirimu?",
    "Apa kenangan yang masih sering membuatmu tersenyum meski kita sudah berpisah?",
    "Menurutmu, apa tujuan kita jika suatu hari kembali bersama?",
    "Apa yang membuatmu merasa hubungan kita dulu tidak memiliki masa depan?",
    "Jika kita menikah, apa yang paling kamu takutkan akan terjadi?",
    "Apa pendapatmu tentang kejujuran dalam hubungan? Apakah aku cukup jujur dulu?",
    "Apa alasan sebenarnya kamu tetap ingin berkomunikasi denganku?",
    "Apakah kamu pernah merasa aku tidak cukup menghargaimu?",
    "Apa yang membuatmu ragu untuk mencoba memperbaiki hubungan kita?",
    "Menurutmu, apa hal yang paling sering kita abaikan dalam hubungan kita dulu?",
    "Apakah kamu percaya kita bisa bahagia jika memulai semuanya dari awal?",
    "Apa yang kamu pikirkan ketika melihat pasangan lain terlihat bahagia?",
    "Menurutmu, apakah aku pernah membuatmu merasa tidak dihargai?",
    "Jika ada orang ketiga dalam hubungan kita dulu, apakah kamu merasa itu salahku?",
    "Apa hal kecil dariku yang masih kamu rindukan hingga sekarang?",
    "Jika kita balikan, apa hal yang menurutmu harus kita ubah bersama?",
    "Menurutmu, apakah aku sudah cukup menunjukkan rasa cinta dan perhatian?",
    "Apa pendapatmu tentang masa depan kita jika kita memutuskan untuk bersama lagi?",
    "Apa perasaanmu jika aku menikah dengan orang lain?",
    "Apa yang membuatmu yakin atau tidak yakin tentang perasaan kita saat ini?",
    "Menurutmu, apa tujuan utama dari sebuah hubungan yang berhasil?",
    "Apa yang kamu rasakan ketika mendengar tentang pasangan lain yang bisa kembali bersama?",
    "Menurutmu, apa yang salah dengan cara kita menyelesaikan masalah dulu?",
    "Apakah kamu merasa aku pernah terlalu sibuk untuk memperhatikan hubungan kita?",
    "Apa yang membuatmu merasa kita tidak memiliki masa depan bersama?",
    "Apakah kamu percaya hubungan kita dulu gagal karena kurangnya komunikasi?",
    "Menurutmu, apakah perselingkuhan bisa dimaafkan jika masih ada cinta?",
    "Jika aku salah, apakah kamu merasa aku selalu mau meminta maaf?",
    "Apa hal terbesar yang kamu pelajari dari hubungan kita?",
    "Jika kita balikan, apakah kamu percaya kita bisa mengatasi semua masalah bersama?",
    "Apa perasaanmu ketika aku memilih untuk melepaskan hubungan kita dulu?",
    "Menurutmu, apa arti cinta sejati dalam hubungan?",
    "Apa hal yang paling kamu rindukan tentang aku setelah kita berpisah?",
    "Apakah kamu merasa ada yang salah dengan cara kita mencintai satu sama lain dulu?",
    "Apa tujuan terbesar kamu dalam hubungan yang ingin kamu bangun ke depannya?",
    "Apa yang menurutmu bisa menghancurkan hubungan, bahkan jika ada cinta?",
    "Menurutmu, apakah aku cukup berjuang untuk mempertahankan hubungan kita dulu?",
    "Apa yang membuatmu merasa bahwa hubungan kita tidak layak untuk diperjuangkan lagi?",
    "Menurutmu, apakah orang ketiga bisa menghancurkan hubungan jika cinta masih kuat?",
    "Apa perasaanmu ketika aku mulai menjauh dari hubungan kita dulu?",
    "Apakah kamu merasa hubungan kita dulu lebih banyak memberikan luka atau kebahagiaan?",
    "Apa alasan utama kamu masih memikirkan tentang hubungan kita?",
    "Menurutmu, apa tujuan utama dari sebuah hubungan yang ingin menuju pernikahan?",
    "Apa pendapatmu tentang kepercayaan dalam hubungan? Apakah aku cukup mempercayaimu?",
    "Apa yang menurutmu perlu aku perbaiki agar menjadi pasangan yang lebih baik?",
    "Jika aku kembali ke hidupmu, apa hal yang paling kamu khawatirkan?",
    "Menurutmu, apakah aku lebih sering membuatmu bahagia atau kecewa?",
    "Apa alasan terbesar kamu merasa hubungan kita dulu tidak berhasil?",
    "Apa yang kamu pikirkan ketika aku lebih fokus pada hal lain dibandingkan hubungan kita?",
    "Apakah kamu percaya hubungan kita dulu gagal karena kurangnya waktu bersama?",
    "Apa pendapatmu tentang pernikahan? Apakah kamu merasa kita cocok untuk itu?",
    "Apa yang membuatmu merasa kita tidak cukup memahami satu sama lain?",
    "Apa kenangan terbaik kita yang menurutmu tak akan pernah bisa tergantikan?",
    "Apa hal yang paling kamu takutkan jika kita kembali menjalin hubungan?",
    "Menurutmu, apakah aku cukup menunjukkan komitmen dalam hubungan kita dulu?",
    "Apa perasaanmu ketika aku terlihat bahagia tanpa dirimu?",
    "Jika kita menikah, apa yang menurutmu akan menjadi tantangan terbesar kita?",
    "Menurutmu, apakah aku orang yang tepat untuk masa depanmu?",
    "Apa yang menurutmu menjadi alasan utama hubungan kita dulu berakhir?",
    "Apa pendapatmu tentang cinta tanpa komitmen? Apakah itu pernah terjadi di hubungan kita?",
    "Menurutmu, apakah hubungan kita dulu berakhir karena kurangnya rasa percaya?",
    "Apa yang membuatmu merasa hubungan kita tidak cukup kuat untuk bertahan?",
    "Apa hal terbesar yang menurutmu salah dalam cara kita berkomunikasi dulu?",
    "Jika kita mencoba lagi, apa yang menurutmu harus aku ubah tentang diriku?",
    "Apa yang kamu pikirkan tentang perasaan yang belum selesai di antara kita?",
    "Apa hal paling menyakitkan yang aku lakukan selama kita bersama?",
    "Menurutmu, apakah hubungan kita dulu berakhir karena kita kurang dewasa?",
    "Apa yang membuatmu merasa ragu untuk membuka hatimu lagi untukku?",
    "Menurutmu, apakah aku orang yang bisa membuatmu bahagia di masa depan?",
    "Kalau mantanmu datang lagi, apa kamu akan menerimanya?",
    "Apa kamu pernah menyalahkan dirimu sendiri atas berakhirnya hubungan dengan mantanmu?",
    "Apa hal terbaik yang pernah kamu pelajari dari mantanmu?",
    "Apa kamu pernah merasa mantanmu adalah orang yang tepat di waktu yang salah?",
    "Apa kamu pernah diam-diam berharap bisa kembali dengan mantanmu?",
    "Menurutmu, siapa yang paling bersalah saat hubungan dengan mantanmu berakhir?",
    "Apa kamu masih menyimpan barang dari mantanmu?",
    "Apa kamu pernah memimpikan mantanmu setelah putus?",
    "Apa alasan terbesar kamu memutuskan hubungan dengan mantanmu?",
    "Apa mantanmu pernah mencoba menghubungimu setelah putus?",
    "Kalau mantanmu minta maaf, apa kamu akan memaafkannya?",
    "Apa kamu pernah curhat tentang pasanganmu saat ini ke mantanmu?",
    "Apa kamu pernah stalking media sosial mantan setelah putus?",
    "Apa mantanmu tahu semua rahasia terdalam yang kamu miliki?",
    "Apa kamu pernah merasa bahagia setelah putus dengan mantanmu?",
    "Apa hal paling memalukan yang pernah terjadi antara kamu dan mantanmu?",
    "Apa menurutmu mantanmu lebih baik dari pasanganmu sekarang?",
    "Apa kamu pernah membandingkan pasanganmu sekarang dengan mantanmu?",
    "Apa ada sesuatu yang kamu sesali dari hubunganmu dengan mantanmu?",
    "Apa alasan sebenarnya kamu mau pacaran sama aku dulu?",
    "Apa hal yang paling kamu rindukan tentang hubungan kita?",
    "Kalau bisa mengulang waktu, apa yang ingin kamu perbaiki di hubungan kita?",
    "Apa aku pernah bikin kamu merasa sangat bahagia?",
    "Apa ada sesuatu yang belum sempat kamu ucapkan ke aku?",
    "Apa kamu pernah bohong selama kita pacaran?",
    "Siapa orang pertama yang kamu ceritakan tentang hubungan kita?",
    "Apa kamu pernah merasa hubungan kita adalah sebuah kesalahan?",
    "Apa aku pernah bikin kamu nangis?",
    "Kalau kita nggak putus, menurutmu hubungan kita akan seperti apa sekarang?",
    "Apa hal paling menyebalkan yang aku lakukan selama kita pacaran?",
    "Apa ada momen yang bikin kamu sadar kita nggak cocok?",
    "Apa kamu pernah merasa lebih nyaman dengan orang lain saat kita masih pacaran?",
    "Apa ada hal baik yang kamu pelajari dari hubungan kita?",
    "Apa kamu masih menyimpan sesuatu yang aku kasih?",
    "Apa kamu pernah cerita tentang aku ke pasanganmu sekarang?",
    "Kalau aku ngajak balikan, apa yang akan kamu katakan?",
    "Apa kamu merasa aku lebih cocok sebagai teman daripada pasangan?",
    "Apa kamu pernah pura-pura bahagia saat kita masih bersama?",
    "Apa alasanmu sebenarnya saat kamu memutuskan untuk putus?",
    "Apa kamu pernah membayangkan masa depan bersama aku?",
    "Kalau kita nggak pacaran, apa kamu pikir kita bisa jadi teman yang baik?",
    "Apa ada orang lain yang kamu sukai saat kita masih bersama?",
    "Menurutmu, apa aku lebih banyak memberikan kebahagiaan atau kesedihan?",
    "Apa ada sesuatu tentang aku yang kamu harap bisa kamu lupakan?",
    "Apa kamu pernah menyesali keputusan kita untuk putus?",
    "Apa kamu merasa hubungan kita berakhir di waktu yang tepat?",
    "Apa aku pernah menjadi alasan kamu kehilangan kepercayaan diri?",
    "Kalau kita bertemu lagi dalam 10 tahun, menurutmu apa yang akan kita bicarakan?",
    "Apa aku adalah mantan yang paling berkesan buat kamu?",
    "Pernah ngerasa baper sama temen sendiri? Kalau iya, siapa?",
    "Kebohongan terbesar apa yang pernah kamu bikin?",
    "Aplikasi yang paling sering kamu buka pas lagi galau?",
    "Kapan terakhir kali kamu cemburu sama gebetan atau pacar?",
    "Siapa yang sering kamu kepoin diam-diam di sosmed?",
    "Pernah simpan chat penting di arsip biar nggak ketahuan orang lain?",
    "Lebih suka temenan atau pacaran sama sahabat?",
    "Menurut kamu, apa hal yang paling nggak guna kamu pernah beli?",
    "Kalau bisa ngulang satu momen dalam hidup, itu kapan dan kenapa?",
    "Pernah nggak ngaku-ngaku jomblo padahal punya pacar?",
    "Apa yang paling kamu nggak suka dari gebetan atau pacar?",
    "Siapa orang terakhir yang kamu blokir di medsos?",
    "Pernah chattingan intens tapi sama sekali nggak ada perasaan?",
    "Apa hal paling konyol yang pernah kamu bilang ke gebetan?",
    "Kalau bisa jadi orang lain selama sehari, kamu mau jadi siapa?",
    "Pernah nggak pura-pura nggak lihat pesan biar nggak perlu bales?",
    "Apa momen paling awkward pas ketemu sama gebetan?",
    "Kalau disuruh pilih, kamu pilih uang atau cinta?",
    "Apa sih hal yang paling kamu cari di sosmed tiap hari?",
    "Siapa orang yang paling sering bikin kamu senyum-senyum sendiri?",
    "Apa kejadian paling memalukan yang pernah kamu alamin di tempat umum?",
    "Pernah ngechat random ke mantan cuma buat lihat dia bales atau nggak?",
    "Kalau bisa hapus satu memori dalam hidup, memori apa yang mau dihapus?",
    "Siapa orang yang paling sering ada di kepala kamu?",
    "Apa perasaan kamu tentang relationship sekarang?",
    "Apa kebohongan paling sering kamu omongin waktu PDKT?",
    "Pernah kepergok stalking akun sosmed seseorang?",
    "Pernah nggak makan sesuatu yang udah jatuh ke lantai?",
    "Kalau disuruh pilih, kamu pilih jadi orang ganteng/cantik atau kaya raya?",
    "Apa hal paling absurd yang pernah kamu googling?",
    "Siapa orang yang paling sering bikin kamu kesel?",
    "Pernah nggak nyanyi sambil mandi tapi suaranya kayak konser gagal?",
    "Pernah pura-pura ngerti omongan orang padahal nggak paham sama sekali?",
    "Siapa orang yang pengen kamu hilangin dari group chat?",
    "Pernah nggak tidur sambil ngorok dan ketahuan orang lain?",
    "Apa hal teraneh yang pernah kamu lakukan saat nggak ada orang?",
    "Kalau bisa teleport ke mana aja, kamu mau teleport ke mana?",
    "Pernah ketiduran pas lagi video call atau voice call?",
    "Apa alasan teraneh yang pernah kamu pakai buat bolos?",
    "Kebiasaan jelek apa yang paling kamu sembunyiin dari orang lain?",
    "Pernah makan diam-diam biar nggak bagi-bagi ke orang lain?",
    "Siapa orang yang terakhir kali kamu mute di sosmed?",
    "Pernah pura-pura sakit biar nggak keluar rumah?",
    "Kapan terakhir kali kamu marah tanpa alasan yang jelas?",
    "Siapa orang yang sering kamu stalking tapi malu kalau ketahuan?",
    "Hal paling absurd apa yang pernah kamu bawa ke sekolah/kantor?",
    "Pernah bohong soal umur demi dapetin diskon?",
    "Apa hal terkonyol yang pernah kamu lakuin demi gebetan?",
    "Pernah nggak tiba-tiba ingat sesuatu yang bikin malu dan ketawa sendiri?",
    "Apa hal paling aneh yang pernah kamu ketahui tentang teman terdekat?",
    "Kapan terakhir kali kamu salah chat dan bikin malu?",
    "Pernah ketahuan ngupil di tempat umum?",
    "Pernah lupa pakai barang sendiri dan panik nyari-nyari?",
    "Kapan terakhir kali kamu pura-pura sibuk padahal lagi gabut?",
    "Pernah nyimpen chat penting biar nggak ketahuan siapa-siapa?",
    "Apa hal yang selalu bikin kamu ngakak tiap kali keingat?",
    "Pernah ngaku nggak ada duit tapi baru aja beli sesuatu mahal?",
    "Pernah ngambil makanan orang lain tanpa izin?",
    "Pernah nggak sok tahu tapi akhirnya ketahuan kalau nggak tahu apa-apa?",
    "Kamu lebih suka jadi terkenal di sosmed atau di dunia nyata?",
    "Apa hal paling nyeleneh yang pernah kamu beli online?",
    "Siapa orang yang paling sering kamu mimpiin akhir-akhir ini?",
    "Pernah bikin akun fake buat stalking orang?",
    "Pernah bohong soal hobi atau minat biar terlihat keren?",
    "Apa barang paling aneh yang ada di tas kamu sekarang?",
    "Siapa yang paling sering bikin kamu cemburu?",
    "Pernah nggak pura-pura nggak lihat temen pas ketemu di tempat umum?",
    "Apa hal paling lucu yang kamu ingat dari masa kecil?",
    "Kalau bisa jadi karakter film, kamu mau jadi siapa?",
    "Pernah nggak salah kirim pesan terus malu banget?",
    "Apa hal yang paling sering kamu stalking di sosmed orang?",
    "Kapan terakhir kali kamu salah sebut nama orang?",
    "Siapa orang yang paling nggak bisa kamu tahan buat digodain?",
    "Apa kebiasaan paling aneh yang kamu lakukan setiap hari?",
    "Kalau bisa punya satu superpower, kamu mau punya apa?",
    "Pernah ngasih kode ke orang tapi dia sama sekali nggak nangkep?",
    "Apa hal paling nyesel yang pernah kamu lakukan waktu mabuk cinta?",
    "Siapa orang yang selalu berhasil bikin kamu tersenyum?",
    "Apa hal pertama yang akan kamu beli kalau tiba-tiba jadi kaya raya?",
    "Pernah nggak ngechat mantan cuma buat lihat apakah dia bales?",
    "Apa hal paling gila yang pernah kamu lakuin demi challenge?",
    "Pernah nggak ngelakuin sesuatu konyol terus pura-pura lupa?",
    "Kapan terakhir kali kamu nangis karena hal remeh?",
    "Siapa orang yang paling sering bikin kamu ngakak sampai sakit perut?",
    "Pernah nggak lupa ngunci pintu terus ketahuan orang lain?",
    "Apa rumor teraneh yang pernah kamu dengar tentang diri sendiri?",
    "Pernah salah ucap kata-kata pas lagi pidato atau presentasi?",
    "Kalau harus pilih, kamu mau bisa baca pikiran atau nggak kelihatan?",
    "Apa momen paling awkward pas ketemu sama orang baru?",
    "Siapa orang yang paling sering kamu ceritain ke temen?",
    "Pernah nggak makan makanan aneh cuma buat penasaran rasanya?",
    "Kalau kamu bisa reset hidup kamu, mau mulai dari umur berapa?",
    "Apa ketakutan terbesar yang kamu sembunyiin dari orang lain?",
    "Apa hal yang bikin kamu paling insecure?",
    "Siapa orang yang paling sering kamu banding-bandingin sama diri sendiri?",
    "Kamu lebih nyaman jadi orang yang terbuka atau tertutup?",
    "Apa kebiasaan buruk yang kamu lakuin tapi kamu nggak bisa berhenti?",
    "Apa hal yang paling bikin kamu nyesel selama hidup?",
    "Siapa orang yang pernah kamu sakiti tapi belum pernah kamu minta maaf?",
    "Apa hal yang kamu harap orang lain nggak pernah tahu tentang kamu?",
    "Siapa orang yang diam-diam kamu kagumi tapi nggak berani bilang?",
    "Apa impian terbesar kamu yang belum tercapai sampai sekarang?",
    "Apa kejadian masa lalu yang selalu teringat dan bikin sedih?",
    "Apa sifat buruk kamu yang paling sering bikin orang lain kesel?",
    "Siapa orang yang paling bikin kamu nyaman buat curhat?",
    "Kapan terakhir kali kamu nangis karena merasa nggak cukup baik?",
    "Apa hal yang bikin kamu paling nggak bisa tidur di malam hari?",
    "Pernah nggak merasa iri sama hidup orang lain? Kalau iya, kenapa?",
    "Apa hal paling aneh yang selalu kamu pikirin tapi nggak pernah kamu omongin?",
    "Siapa orang yang paling bikin kamu merasa diterima apa adanya?",
    "Kalau kamu bisa ngubah satu hal dari diri sendiri, itu apa?",
    "Pernah nggak pura-pura bahagia padahal hati kamu hancur?",
    "Apa sifat atau perilaku orang yang paling kamu benci?",
    "Kalau bisa minta maaf ke seseorang yang udah nggak ada di hidup kamu, siapa itu?",
    "Siapa orang yang paling bikin kamu terinspirasi?",
    "Apa hal yang paling kamu takutin orang lain tahu tentang kamu?",
    "Pernah nggak merasa nggak punya siapa-siapa meski banyak temen?",
    "Apa rahasia terbesar kamu yang nggak pernah kamu ceritain ke siapa-siapa?",
    "Pernah nggak merasa minder pas ngumpul sama temen-temen?",
    "Apa sifat yang paling kamu suka dan nggak suka dari diri kamu sendiri?",
    "Kalau dikasih kesempatan minta maaf ke seseorang, kamu pilih siapa?",
    "Siapa orang yang paling berpengaruh di hidup kamu?",
    "Pernah nggak kamu merasa gagal atau nggak berguna?",
    "Apa hal yang selalu bikin kamu semangat pas lagi down?",
    "Siapa orang yang paling kamu pengen banggain dengan kesuksesan kamu?",
    "Pernah nggak nyembunyiin sesuatu dari orang tua karena takut kecewain mereka?",
    "Apa sifat yang kamu pengen orang lain lihat dari kamu?",
    "Pernah nggak kamu ngerasa nggak disukai sama lingkungan sekitar?",
    "Apa hal yang selalu bikin kamu lega pas lagi stres berat?",
    "Kalau bisa kasih saran ke diri sendiri di masa lalu, kamu mau bilang apa?",
    "Apa momen yang bikin kamu sadar kalau hidup nggak selalu adil?",
    "Siapa orang yang pengen kamu lindungi dari segala hal buruk di dunia ini?",
    "Pernah nggak merasa diri kamu nggak sebaik yang orang kira?",
    "Kalau harus jujur, apa hal yang paling kamu takutin dalam hidup ini?",
    "Siapa orang yang paling sering kamu pikirin sebelum tidur?",
    "Apa hal paling berani yang pernah kamu lakukan dalam hidup?",
    "Apa kenangan masa kecil yang masih bikin kamu tersenyum?",
    "Siapa yang paling kamu takutin kehilangannya di dunia ini?",
    "Apa pelajaran hidup yang paling berharga buat kamu?",
    "Pernah nggak kamu ngaku bahagia padahal nggak sama sekali?",
    "Kalau bisa ngubah satu kenangan dalam hidup, apa yang mau kamu ubah?",
    "Apa keputusan terbesar yang pernah kamu ambil?",
    "Apa cita-cita waktu kecil yang sampai sekarang masih pengen dicapai?",
    "Siapa orang yang paling bikin kamu ngerasa diterima tanpa syarat?",
    "Apa hal kecil yang selalu bikin kamu bahagia tiap hari?",
    "Pernah nggak kamu merasa nggak layak dicintai?",
    "Apa hal paling penting yang pernah kamu pelajari dari kegagalan?",
    "Kalau kamu harus mengungkapin satu perasaan terpendam ke seseorang, apa itu?",
    "Siapa yang paling kamu harap selalu ada di hidup kamu?"
];

// Fungsi untuk mengambil pertanyaan random
let handler = async (m, { conn }) => {
    let randomTruth = truths[Math.floor(Math.random() * truths.length)];
    await conn.reply(m.chat, `*TRUTH*\n\n“${randomTruth}”`, m);
}

handler.help = ['truth'];
handler.tags = ['fun'];
handler.command = /^(truth|kebenaran|kejujuran)$/i;
handler.limit = true;

module.exports = handler;